name: Deploy DEV

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    name: Create PR for PRE-PROD
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v6

      - name: Create PR from develop to sim
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Promote develop to sim"
          body: |
            Automatically created after successful develop pull request.
          delete-branch: true