name: Shared CI Pipeline

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/build-project.yaml

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Simulate tests
        run: |
          echo "======================"
          echo "TEST STAGE"
          echo "Running unit tests"
          echo "Running integration tests"
          echo "Running quality checks"
          echo "All tests passed"
          echo "======================"