name: Continuous Deployment

on:
  push:
    branches:
      - main
      - sim

jobs:
  build:
    uses: ./.github/workflows/build-project.yaml

  deploy:
    name: Deploy to ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Pre-prod' }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'pre-prod' }}
    needs: build

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: build-artifact

      - name: Simulate ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Pre-prod' }} deployment
        run: |
          echo "======================"
          echo "DEPLOYMENT - ${{ github.ref == 'refs/heads/main' && 'PROD' || 'PRE-PROD' }}"
          echo "Deploying release to server ${{ vars.WEB_APP_NAME }}"
          echo "Restarting services"
          echo "======================"